name: kdiskmark
version: '3.1.2'
summary: A simple open-source disk benchmark tool for Linux distros
description: |
  HDD and SSD benchmark tool with a very friendly graphical user interface.
license: GPL-3.0
base: core18

grade: stable
confinement: strict

architectures:
  - build-on: amd64

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  kdiskmark:
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DROOT_EDITION=OFF
      - -DSNAP_EDITION=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-snaps:
      - cmake
      - kde-frameworks-5-core18
      - kde-frameworks-5-core18-sdk
    build-packages:
      - qttools5-dev
      - qttools5-dev-tools # Qt5LinguistTools
      - extra-cmake-modules
      - libqt5svg5-dev
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=kdiskmark|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/kdiskmark.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/kdiskmark.desktop
    organize:
      usr/share/qt5/translations/*.qm: usr/share/kdiskmark/translations/
    source: https://github.com/JonMagon/KDiskMark.git
    source-commit: b411c4ae0d4a4ab23531ae1fecddcf76a493a515

  runtime:
    plugin: nil
    stage-packages:
      - fio
      - libdouble-conversion1
      - libfreetype6
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libharfbuzz0b
      - libicu60
      - libpng16-16
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libqt5svg5
      - kde-style-breeze
      - breeze-icon-theme
    prime:
      - "-usr/share/fonts/*"
      # https://forum.snapcraft.io/t/kde-neon-extension-libqt5core-so-5-version-qt-5-12-not-found/13744
      # libquazip5-1 pulls in Qt5 from bionic as a dependency. We don't
      # want it in our snap, however, because we get a newer Qt5 from the
      # kde-kf5 platform snap.
      - "-usr/lib/x86_64-linux-gnu/libQt5*"
      - "-usr/lib/x86_64-linux-gnu/libqt5*"

apps:
  kdiskmark:
    extensions:
      - kde-neon
    command: usr/bin/kdiskmark
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - x11
      - home
      - mount-observe
      - hardware-observe
      - udisks2
      - removable-media
      - process-control
      # https://forum.snapcraft.io/t/possibly-missing-apparmor-network-permission/15054/29
      # This interface workarounds a crash on launch due to the denied
      # dac_read_search capability usage
      - system-backup
      # https://forum.snapcraft.io/t/log-observe-autoconnect-request-for-soscleaner/17072/9
      # This interface workarounds a permission denied error when starting
      # a benchmark due to the denied dac_override capability usage
      - log-observe
    desktop: usr/share/applications/kdiskmark.desktop
